# Generated by Django 2.2.3 on 2019-08-27 02:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_aditem'),
    ]

    operations = [
        migrations.AddField(
            model_name='aditem',
            name='brief',
            field=models.CharField(default=11, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aditem',
            name='title',
            field=models.CharField(default=django.utils.timezone.now, max_length=30),
            preserve_default=False,
        ),
    ]
