# Generated by Django 2.2.3 on 2019-08-27 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_auto_20190826_2210'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aditem',
            old_name='order',
            new_name='item',
        ),
    ]
