# Generated by Django 2.2.3 on 2019-08-27 23:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_auto_20190826_2222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aditem',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AdItem', to='order.Item'),
        ),
        migrations.CreateModel(
            name='ItemImg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='order.Item')),
            ],
        ),
    ]
