# Generated by Django 2.2.3 on 2019-08-27 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_auto_20190827_1947'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ItemImg',
            new_name='ItemDetailImg',
        ),
    ]
