# Generated by Django 2.2.3 on 2019-09-02 22:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_auto_20190902_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemdetailimg',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detail_image', to='order.Item'),
        ),
    ]
