# Generated by Django 2.2.3 on 2019-09-02 22:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_auto_20190902_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemdetailimg',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.Item'),
        ),
    ]
