# Generated by Django 2.2.3 on 2019-09-02 23:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_auto_20190902_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemdetailimg',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='order.Item'),
        ),
    ]
